# Generated by Django 4.2.9 on 2024-03-29 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='konto',
            name='username',
        ),
    ]
