# Generated by Django 4.2.9 on 2024-03-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0002_remove_konto_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='konto',
            name='username',
            field=models.CharField(default='test', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
