# Generated by Django 4.2.9 on 2024-03-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konta', '0003_konto_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='konto',
            options={'verbose_name': 'konto', 'verbose_name_plural': 'konta'},
        ),
        migrations.RemoveField(
            model_name='konto',
            name='phone_number',
        ),
    ]
