# Generated by Django 4.2.9 on 2024-03-30 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produkt',
            options={'verbose_name': 'produkt', 'verbose_name_plural': 'produkty'},
        ),
        migrations.RemoveField(
            model_name='produkt',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='produkt',
            name='stock',
            field=models.IntegerField(blank=True),
        ),
    ]
