# Generated by Django 4.2.9 on 2024-03-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklep', '0002_alter_produkt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
