# Generated by Django 4.2.9 on 2024-03-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria_name', models.CharField(max_length=60)),
                ('kategoria_image', models.ImageField(blank=True, upload_to='photos/kategorie')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'kategoria',
                'verbose_name_plural': 'kategorie',
            },
        ),
    ]
