# Generated by Django 4.2.9 on 2024-03-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linie_zamowien', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liniazamowienia',
            options={'verbose_name': 'linia zamówienia', 'verbose_name_plural': 'linie zamówień'},
        ),
    ]
