# Generated by Django 4.2.9 on 2024-03-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0002_rename_konto_id_zamowienie_konto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zamowienie',
            options={'verbose_name': 'zamówienie', 'verbose_name_plural': 'zamówienia'},
        ),
    ]
