# Generated by Django 4.2.9 on 2024-04-01 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0003_alter_zamowienie_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 1, 17, 5, 24, 9737, tzinfo=datetime.timezone.utc), null=True)),
                ('valid_to', models.DateTimeField(blank=True, default=datetime.datetime(2100, 1, 1, 0, 0), null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
