# Generated by Django 4.2.9 on 2024-04-01 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0004_kupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kupon',
            options={'verbose_name': 'kupony', 'verbose_name_plural': 'kupon'},
        ),
        migrations.AddField(
            model_name='kupon',
            name='redeem_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 1, 19, 49, 43, 300613, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
