# Generated by Django 4.2.9 on 2024-04-02 19:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0005_alter_kupon_options_kupon_redeem_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 2, 19, 50, 11, 185668, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='zamowienie',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
