# Generated by Django 4.2.9 on 2024-04-02 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0006_alter_kupon_valid_from_alter_zamowienie_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 2, 19, 52, 31, 664000, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
