# Generated by Django 4.2.9 on 2024-04-07 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zamowienia', '0012_alter_kupon_valid_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kupon',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 1, 0, 0), null=True),
        ),
    ]
