# Generated by Django 4.2.9 on 2024-03-30 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('koszyki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='koszyk',
            options={'verbose_name': 'koszyk', 'verbose_name_plural': 'koszyki'},
        ),
        migrations.AlterModelOptions(
            name='koszykitem',
            options={'verbose_name': 'produkt w koszyku', 'verbose_name_plural': 'produkty w koszyku'},
        ),
    ]
